travis:
  secure:
    BINSTAR_TOKEN: uQScTdQdIRxaIdafGkhAGoWBfVdugsebR9OxM1HIP14+25l+E03RmlmLn1aTdjK4Ww8ENVzlttoQOgGPxV86xZ0+ovECB4hr6mi/lyai1EdBhRQJX5xeUM5oABuI6klQzSM5CE1AtMc4Ba+kGrrWTs9bVk6yAAI7aPEAu7hsLf2dXNi564cLDbMwFOlWdj0F2Okl8n3u7n6EBP7CzHBLbcZBSNDuZsNQnahjH076r4iEDD5sCyOV9KX80EN536o1O6JZsMr6FzW2t7rPlsV3oSfKS+b/m08ICvuycRsCL1zUdYDURflv6vx2DbICIRcTJkx+pWLXCCCuph1YPmZWHNVRkO4Tkt8q4mBKYT/EVgVLqFRtYhp3PMxB+s0jtkUFjgHMp61AZAO8h8wcytexHf5LjTpYCpSGgvIs/VHcTpXDx7K3wirPC6nJaX9mSbD81o8Dw5lAHDnwuajeE7Y/3qoRRTmKDE4c3dT5/IKCwS1hO9Tu9OB8wnWt6MUfMU9cJbcFOVXZGGhI74Y9rC9fskROUX2LNqTyw0RtSSyceCdOWvj35czTd1kJ/FaZpzEoHhc/DggYgAFmIqUSG/M7uwMgka0hc0Hg5QXeQMFzeWLdMhNhcJG3a2EBeQnFTEGx/3QLzNsbsVVtNY4Pm8n7ZuwxE3jHW1CNDbkNBly57To=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
