travis:
  secure:
    BINSTAR_TOKEN: na4NJIwbqDj48YSH1iZxyi0jRm3w9oJhMt7WUM7je8euIJF/jCehPNDDF+nsx3xRhP/xC/lpHoJvGkcd1TBldk/UooyBHuxVCoyV15CU6Jh47oqw/1HEGL4uNwyagTjJ7Grh/z28BAOTlsza917WDRC8TaG1DT/+oynzKOcrK8ALDTc9qc6bcWyUx/55MAYm2PINAGUNfdoYCYgzYiFuww/TNel+/ARbqBXDSXsa/da0+DLD9NWZVuM/h4ch3NZS1FeX4UThVIz4dHYI3hmb0tZgLsLAWlo2L182KJvSRymztJ+LzlpFA0ZPETOI3BSpvpHfKQHEIfpAtYSNWQ6o4cp6yptKt1KvsdrX6/dv+8qsrzIpitn1V9adp96llV+iHambA8ODF+BxZFcIAuDq6f0qaOsc5lgbjPbCu/5JHRNKW7mIyXkwkxdAfWyI2IWQ28TGCBfYNmpoc+lHtoYAp2QfgKP46F808C9llssR92HUMf00IN4O22J2oA3yXfbDmyi3yP/J12zei0bwCQewt+GWQ8+OV4JZChzfd/vBCfsYWVk5BmzIo8hjkXlYqBXCcc3vxpd+/pbN+1m3KpTwfoXYnShwkmapZABviqx2vanxfDvqXirHak9v8zAL7hGj9E0O3/lo5ibhnNwPdC1RBple2xf01xEv5Evkx+cwZAQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
