travis:
  secure:
    BINSTAR_TOKEN: tyOgijmZ+TAmNekM6r7HsAsNk+wRzRaVyZfI3ytlc1UvncnEjlYv7nJpi/MopxG+eZXkLVitvlehs3tM60C8pw6OxDVYWt1u/gdN/iVjhz/FzBEIAOP3hvxANYMeK7e0G4XQTWqMIMdoDdnmY8BlXD92zX3jnnJ7FvExgtExPOPXoDkg0uUZPs/hHCSk9vhpMp7n9B4SfjqdKcNdLzHTC0nTpg64icGecDz9WfBWPIoBW09N/eZittNhX9R5Pk8Vafvsz6UBu0dbtwFU/nIeNsMOLZoFIS7C/pbd788HU3Hfb1I0pRMFFcmZ8AFK3vxdPh79f0U2UuOHdrlPtK2WuTjilodpxiDnW/5JyvOCKcB5Fzvhf0G71sPOTnkWNZ0cLusajnQPSLmDe8JkjHs9t/k+m5afXBB3pChpQBfHYMWpWn/ZbCEUcN7/wlNoQus+xysAEWC5E9REuB3Sp09hazDbXoruF7oSYFQgC9bXDImcAqGEC6nf7Mz2Bj1I74AxLPplUxiW+12MDtbEW2Gda2134flN2JfIlEHuy+JsQVyjL7OhjaE/Fz69+9pUC/bJ5iijzseRizOhQx43AOQVo+rhbSMF3cA3hZYx40NXP3NjjCWgjyyhI74SMVp1rnUfgqdXCQTLv0rEwoipPmLgAUofLuE9kklO8Tj1TESjoYk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
