travis:
  secure:
    BINSTAR_TOKEN: URj5Zss8RjBKAdkk+eN12aodX+0Ch9f/vtBepFKnbjEHcbNmRSK29KDIk1AUaVwZZ1YMXk8zeeHm3s8cjtjtmKJ1IA4b53qVnEaiZPp6nE105nU+PYeQrrnK0X/Fw0jeXL5u04vtJxLGS9gXqlFSL+5tKy39oVG38+gCCrKJKhwruXhli5K/HD71DPO0oB0J0M2hJhZ0gJutvQsdRB7RLwHxlbpmoL89PxaHUwMusvP4uH5TdXsKUpSIvn3HGhHifLbdoC5EFfYVEtuB1MGOi+86fwUwvTUTDCBAvhj9WR9QcgrIKIGVfVHjClhcqFe1JQVtK5WeFzSunEJadQDlwIL4X3/m4Ypo/dEEPkHI6X8k8M+UGYz4GzQcgjHWWU+MxXubn9xp5aNMQENlQMbIwqS9TxXdh+lACAdlI5ZRpgp/0PMD0B0HbsEfGoKY6nClOC7oOO+4it7S/IP5FV2v9Zo/GywXXyu69ZhUkkCXk6kC9YGv9NlqlxTQesti09tJwpSqnXpgiZc4JXSHNbEJ9su5pLaKokAfgZAAzwQJSxQC3EDMAP1rkdAu/3uX0RDL4Vq2xvRcnlvL6+53/feIvi2yT7ee/yc880El05Chi2CMVcqgW9eOgVbltdA0XR5QE7+WTZex9ML79l/6leC4EyWJAxYtaU6SONAGjgSgTyQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
